# Generated by Django 4.2.7 on 2023-11-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='fecha',
            field=models.DateField(),
        ),
    ]
